### ISSUE TITLE
[CD] Make 'tests.yml' workflow more DRY

### ISSUE THREAD

**Issue by Privat33r-dev** [nikitastupin/clairvoyance#90]
Currently the following lines are repetitive. It would be nice to make them follow the Do-Not-repeat-Yourself principle by separating them in another action/workflow.
```yaml
    - uses: actions/checkout@v4
    - name: Install and configure poetry
      run: |
        pipx install poetry
        poetry config virtualenvs.in-project true
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'poetry'
    - name: Setup poetry
      run: poetry install
```
